Update post.py
Error: " TypeError: unsupported operand type(s) for |: 'str' and 'type'"

Solution: Since I've faced issues in the past with having the model encapsulate another data type (it can cause an infiinite loop since the User contains a list of posts)  I have decided that the Post will hold User information by holding the poster's PID or just primary key ID number.