Fix typo in our User model
Error: TypeError: 'type' object does not support item assignment

Solution: removed the first = sign because it was supposed to be a colon (:). No idea why I typed it worng in the first place.