Implement the tag categorization in the front end and Edit the delete method in post service (#53)
* add delete feature into post and add unit test

* Temporarily fix the problem in creating post.

However, we currently do not have the comment feature in create post

* implement the autocomplete chip into the tags entry, still need some adjustment

* add authorization in delete_post and the corresponding unit test

* complete the autocompletion for tags categorization

* resolve merge conflicts

* Fix the post_test (I accidentally overwrite the post_test in the last commit )

* continuing fix the delete feature of posts

I think I have the similar problem as last time. Last time the problem was on we should not create multiple sessions in post service. This time I can not use self._permission in post service and have the error like this :  def delete_post(self, id: int, subject: User) -> Post | None:
        admin = False
>       perm = self._permission.get_permissions(subject)
E       AttributeError: 'function' object has no attribute 'get_permissions'

backend/services/post.py:53: AttributeError

* finally fixed the delete post

I originally have the attribute error for permission service. It turned out the self._permission is class function instead of permission service. I changed that in the post service init. and now it worked fine. I also added the corresponding unit test for authorization.