Update comment.py
Error: TypeError: unsupported operand type(s) for |: 'str' and 'type'

Solution: see previous commit about the updates to post.

Comment will hold the primary key or PID of the User and primary key of the post.