Data models wip (#19)
* Add post and comment model

* Add team model

* Update user.py to include posts and teams

* update entities

none have been tests, updates based on my code and kris jordan's

added comment, post, and team according to models created previously

reply and membership are association tables

* Update user_entity.py

updated to match previous updates to model.

methods were also updated.

nothiing tested so far.

TODO: update creation and reset of databse.

* Fix typo in our User model

Error: TypeError: 'type' object does not support item assignment

Solution: removed the first = sign because it was supposed to be a colon (:). No idea why I typed it worng in the first place.

* Update post.py

added this line because I thought it might be necessary to have a default value here.

* Update post.py

Error: " TypeError: unsupported operand type(s) for |: 'str' and 'type'"

Solution: Since I've faced issues in the past with having the model encapsulate another data type (it can cause an infiinite loop since the User contains a list of posts)  I have decided that the Post will hold User information by holding the poster's PID or just primary key ID number.

* Update comment.py

Error: TypeError: unsupported operand type(s) for |: 'str' and 'type'

Solution: see previous commit about the updates to post.

Comment will hold the primary key or PID of the User and primary key of the post.

* Update team.py

Error: TypeError: 'type' object does not support item assignment

Solution: see previous commit about the updates to User model

* Update team_entity.py

potential fix, devcontainer not working

but basically it should backpopulate the corract propety in User entity